# Generated by Django 4.1.7 on 2023-03-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_management", "0002_asset_acquisition_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="category",
            field=models.CharField(
                choices=[("hardware", "硬件"), ("software", "软件"), ("other", "其他")],
                default="hardware",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[("in_use", "使用中"), ("in_storage", "仓库中"), ("disposed", "已处置")],
                default="in_use",
                max_length=50,
            ),
        ),
    ]
