# Generated by Django 4.1.7 on 2023-03-18 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("asset_management", "0004_assetcategory_alter_asset_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="资产状态名称")),
            ],
            options={"verbose_name_plural": "资产状态",},
        ),
        migrations.AlterModelOptions(
            name="assetcategory", options={"verbose_name_plural": "资产分类"},
        ),
        migrations.AddField(
            model_name="asset",
            name="new_category",
            field=models.ForeignKey(
                default=123,
                on_delete=django.db.models.deletion.CASCADE,
                to="asset_management.assetcategory",
                verbose_name="资产分类",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="asset",
            name="category",
            field=models.CharField(
                choices=[("hardware", "硬件"), ("software", "软件"), ("other", "其他")],
                default="hardware",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="assetcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="资产分类名称"),
        ),
        migrations.AddField(
            model_name="asset",
            name="new_status",
            field=models.ForeignKey(
                default=1243,
                on_delete=django.db.models.deletion.CASCADE,
                to="asset_management.assetstatus",
                verbose_name="资产状态",
            ),
            preserve_default=False,
        ),
    ]
