# Generated by Django 4.1.7 on 2023-03-19 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("asset_management", "0006_assetlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(model_name="asset", name="new_category",),
        migrations.RemoveField(model_name="asset", name="new_status",),
        migrations.AlterField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="asset_management.assetcategory",
                verbose_name="资产分类",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="asset_management.assetstatus",
                verbose_name="资产状态",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="asset_management.employee",
            ),
        ),
    ]
