# Generated by Django 4.1.7 on 2023-03-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "asset_management",
            "0008_employee_department_employee_position_employee_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_scrapped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assetlog",
            name="return_status",
            field=models.BooleanField(default=False),
        ),
    ]
