# Generated by Django 4.1.7 on 2023-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_management", "0009_asset_is_scrapped_assetlog_return_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcategory",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
