# Generated by Django 4.1.7 on 2023-03-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_management", "0012_assetlending"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="assets/"),
        ),
    ]
