# Generated by Django 4.1.7 on 2023-04-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_management", "0014_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftwareLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="软件名称")),
                ("license_key", models.CharField(max_length=255, verbose_name="许可证密钥")),
                ("purchase_date", models.DateField(verbose_name="购买日期")),
                ("expiration_date", models.DateField(verbose_name="到期日期")),
                ("vendor", models.CharField(max_length=100, verbose_name="供应商")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
            ],
            options={"verbose_name_plural": "软件许可证",},
        ),
    ]
